// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Local `prisma dev` serves a shadow database on a second port;
    // hosted Prisma Postgres doesn't need this.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
